version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo "Installing dependencies..."
      - npm install  
          
  build: 
    commands:
      - echo "Building the React application..."
      - npm run build 
      - echo "Syncing to S3..."
      - aws s3 sync build/ s3://anewnameiassingtothisbucket2025/ --delete
             
artifacts:
  files:
    - '**/*'
  discard-paths: yes

