AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyWebsiteBucket:
    Type: 'AWS::S3::Bucket'
    Properties: 
      BucketName: "anewnameiassingtothisbucket2025"
      WebsiteConfiguration:
        IndexDocument: "index.html"
        ErrorDocument: "error.html"

  MyS3BucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref MyWebsiteBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "AllowCompanyIPs"
            Effect: "Allow"
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub "arn:aws:s3:::${MyWebsiteBucket}/*"
            Condition:
              IpAddress:
                aws:SourceIp:
                  - "185.134.130.79"
          - Sid: "DenyAllOtherIPs"
            Effect: "Deny"
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub "arn:aws:s3:::${MyWebsiteBucket}/*"

